---
- name: "systemd root config"
  template:
    src: "systemd.service"
    dest: "/etc/systemd/system/{{item.name}}.service"
    owner: "{{tiddlywiki_systemd_user}}"
    group: "{{tiddlywiki_systemd_group}}"
  with_items: "{{tiddlywiki_instances}}"
  when: tiddlywiki_systemd_user == "root"
- name: "ensure systemd user path exists"
  file:
    path: "{{tiddlywiki_systemd_home}}/{{tiddlywiki_systemd_user}}/.config/systemd/user"
    state: directory
    owner: "{{tiddlywiki_systemd_user}}"
    group: "{{tiddlywiki_systemd_group}}"
    mode: 0770
  when: tiddlywiki_systemd_user != "root"
- name: "systemd user config"
  template:
    src: "systemd.service"
    dest: "{{tiddlywiki_systemd_home}}/{{tiddlywiki_systemd_user}}/.config/systemd/user/{{item.name}}.service"
    owner: "{{tiddlywiki_systemd_user}}"
    group: "{{tiddlywiki_systemd_group}}"
    mode: 0660
  when: tiddlywiki_systemd_user != "root"
  with_items: "{{tiddlywiki_instances}}"
- name: "enable system tiddlywikis"
  service:
    name: "{{item.name}}"
    enabled: "yes"
    state: "started"
  with_items: "{{tiddlywiki_instances}}"
  when: tiddlywiki_systemd_user == "root"
- name: "enable user tiddlywikies"
  systemd:
    name: "{{item.name}}"
    enabled: "yes"
    state: "started"
    user: "yes"
  become: "yes"
  become_user: "{{tiddlywiki_systemd_user}}"
  with_items: "{{tiddlywiki_instances}}"
  when: tiddlywiki_systemd_user != "root"
