---
- npm:
    name: tiddlywiki
    global: true
- name: check for wiki
  stat:
    path: "{{item.path}}"
  register: tiddlywiki_stat
  with_items: "{{tiddlywiki_instances}}"
- name: initialize wiki
  command: tiddlywiki "{{item.item.path}}" --init "{{item.item.edition}}"
  when: not item.stat.exists
  with_items: "{{tiddlywiki_stat.results}}"
- include: "osx.yml"
  when: ansible_system == "Darwin"
- include: "linux.yml"
  when: ansible_system == "Linux"
- name: "create a config directory"
  file:
    path: "{{tiddlywiki_install_directory}}/etc"
    state: directory
    owner: "{{tiddlywiki_owner}}"
    group: "{{tiddlywiki_group}}"
    mode: 0770
- name: "generate tiddlyctl config"
  template:
    src: "tiddlyctl.j2"
    dest: "{{tiddlywiki_install_directory}}/etc/tiddlyctl"
    owner: "{{tiddlywiki_owner}}"
    group: "{{tiddlywiki_group}}"
    mode: 0660
- name: "copy tiddlyctl script"
  copy:
    src: "tiddlyctl.sh"
    dest: "{{tiddlywiki_bin_directory}}/tiddlyctl"
    owner: "{{tiddlywiki_owner}}"
    group: "{{tiddlywiki_group}}"
    mode: "0770"
- name: "generate tiddlyrc"
  template:
    src: "tiddlyrc"
    dest: "{{tiddlywiki_profile_path}}/.tiddlyrc"
    owner: "{{tiddlywiki_owner}}"
    group: "{{tiddlywiki_group}}"
    mode: "0660"
  when: tiddlywiki_rc
