- npm:
    name: tiddlywiki
    global: yes
- name: check for wiki
  stat:
    path: "{{item.path}}"
  register: tiddlywiki_stat
  with_items: "{{tiddlywiki_instances}}"
- name: initialize wiki
  command: tiddlywiki "{{item.item.path}}" --init "{{item.item.edition}}"
  when: not item.stat.exists
  with_items: "{{tiddlywiki_stat.results}}"
- include: "osx.yml"
  when: ansible_system == "Darwin"
- include: "linux.yml"
  when: ansible_system == "Linux"
